-- Seed reference data. Runs after migrations on supabase db reset / supabase start.

-- 1. ATA chapters (must run before acs_code - IDs are referenced)
INSERT INTO public.ata_chapter (chapter_number, title, description) VALUES
('00', 'General', NULL),
('05', 'Time Limits / Maintenance Checks', NULL),
('06', 'Dimensions & Areas', NULL),
('07', 'Lifting & Shoring', NULL),
('08', 'Leveling & Weighing', NULL),
('09', 'Towing & Taxiing', NULL),
('10', 'Parking, Mooring, Storage', NULL),
('11', 'Placards, Markings', NULL),
('12', 'Servicing', NULL),
('20', 'Standard Practices – Airframe', NULL),
('21', 'Air Conditioning', NULL),
('22', 'Auto Flight', NULL),
('23', 'Communications', NULL),
('24', 'Electrical Power', NULL),
('25', 'Equipment & Furnishings', NULL),
('26', 'Fire Protection', NULL),
('27', 'Flight Controls', NULL),
('28', 'Fuel', NULL),
('29', 'Hydraulic Power', NULL),
('30', 'Ice & Rain Protection', NULL),
('31', 'Indicating / Recording Systems', NULL),
('32', 'Landing Gear', NULL),
('33', 'Lights', NULL),
('34', 'Navigation', NULL),
('35', 'Oxygen', NULL),
('36', 'Pneumatic', NULL),
('38', 'Water / Waste', NULL),
('49', 'APU', NULL),
('51', 'Structures - General', NULL),
('52', 'Doors', NULL),
('53', 'Fuselage', NULL),
('54', 'Nacelles / Pylons', NULL),
('55', 'Stabilizers', NULL),
('56', 'Windows', NULL),
('57', 'Wings', NULL),
('61', 'Propellers / Propulsors', NULL),
('62', 'Rotorcraft – Main Rotor', NULL),
('63', 'Rotorcraft – Main Rotor Drive', NULL),
('64', 'Rotorcraft – Tail Rotor', NULL),
('65', 'Rotorcraft – Tail Rotor Drive', NULL),
('70', 'Standard Practices – Engine', NULL),
('71', 'Powerplant', NULL),
('72', 'Engine', NULL),
('73', 'Engine Fuel & Control', NULL),
('74', 'Ignition', NULL),
('75', 'Air', NULL),
('76', 'Engine Controls', NULL),
('77', 'Engine Indicating', NULL),
('78', 'Exhaust', NULL),
('79', 'Oil', NULL),
('80', 'Starting', NULL),
('81', 'Turbines', NULL),
('82', 'Water Injection', NULL),
('83', 'Accessory Gearboxes', NULL),
('84', 'Propeller', NULL);

-- 2. ACS codes
INSERT INTO public.acs_code (code, domain, subject_letter, subject, category, description, ata_chapters)
VALUES
  ('AM.I.A.K1', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Electron theory (conventional flow vs. electron flow).', ARRAY[10,14]::integer[]),
  ('AM.I.A.K2', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Magnetism.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K3', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Capacitance in a circuit.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K4', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Inductance in a circuit.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K5', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Alternating current (AC) electrical circuits.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K6', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Direct current (DC) electrical circuits.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K7', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Electrical laws and theory.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K7a', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Ohm''s Law.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K7b', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Kirchhoff''s Laws.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K7c', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Watt''s Law.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K7d', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Faraday''s Law.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K7e', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Lenz''s Law.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K7f', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Right-hand motor rule.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K8', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Electrical measurement tools, principles, and procedures.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K9', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Voltage (including regulation).', ARRAY[10,14]::integer[]),
  ('AM.I.A.K10', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Current.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K11', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Resistance (impedance, series, parallel, total).', ARRAY[10,14]::integer[]),
  ('AM.I.A.K12', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Power.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K13', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Series circuits.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K14', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Parallel circuits.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K15', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Aircraft batteries.', ARRAY[14]::integer[]),
  ('AM.I.A.K16', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Transformers.', ARRAY[14]::integer[]),
  ('AM.I.A.K17', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Circuit continuity.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K18', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Controlling devices, including switches and relays.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K19', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Protective devices (fuses, circuit breakers, current limiters).', ARRAY[10,14]::integer[]),
  ('AM.I.A.K20', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Resistor types and color coding.', ARRAY[10]::integer[]),
  ('AM.I.A.K21', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Semiconductors (diodes, transistors, integrated circuits).', ARRAY[10]::integer[]),
  ('AM.I.A.K22', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Digital logic (RAM, ROM, NVRAM, logic gates, inverter, rectifier, flip flop).', ARRAY[10]::integer[]),
  ('AM.I.A.K23', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Binary numbers.', ARRAY[10]::integer[]),
  ('AM.I.A.K24', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Electrostatic discharge.', ARRAY[10]::integer[]),
  ('AM.I.A.K25', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Electrical circuit drawings.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K26', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'Complex/combined circuits.', ARRAY[10,14]::integer[]),
  ('AM.I.A.K27', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'knowledge', 'AC and DC motors.', ARRAY[10,14]::integer[]),
  ('AM.I.A.R1', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'risk_management', 'Taking voltage, current, resistance, and capacitance measurements.', ARRAY[10,14]::integer[]),
  ('AM.I.A.R2', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'risk_management', 'Handling, storage, and inspection of batteries.', ARRAY[14]::integer[]),
  ('AM.I.A.R3', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'risk_management', 'High-voltage circuits (e.g., strobe lighting).', ARRAY[14,23]::integer[]),
  ('AM.I.A.R4', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'risk_management', 'Working around batteries.', ARRAY[14]::integer[]),
  ('AM.I.A.S1', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Perform circuit continuity test.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S2', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Measure voltage.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S3', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Measure current.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S4', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Measure resistance.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S5', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Test a switch or relay.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S6', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Test a fuse or circuit breaker.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S7', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Read and interpret aircraft electrical circuit diagrams and symbols.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S8', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Troubleshoot a circuit.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S9', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Identify symbols in electrical/electronic schematic diagrams.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S10', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Demonstrate how to test for short-circuit and open-circuit conditions.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S11', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Measure voltage drop across a resistor.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S12', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Determine or measure for open electrical circuits.', ARRAY[10,14]::integer[]),
  ('AM.I.A.S13', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Inspect an aircraft battery.', ARRAY[14]::integer[]),
  ('AM.I.A.S14', 'general', 'A', 'Fundamentals of Electricity and Electronics', 'skill', 'Service an aircraft battery.', ARRAY[14]::integer[]),
  ('AM.I.B.K1', 'general', 'B', 'Aircraft Drawings', 'knowledge', 'Drawings, blueprints, sketches, charts, graphs, and system schematics.', ARRAY[10]::integer[]),
  ('AM.I.B.K2', 'general', 'B', 'Aircraft Drawings', 'knowledge', 'Repair or alteration using drawings/blueprints to determine type design conformity.', ARRAY[10]::integer[]),
  ('AM.I.B.K3', 'general', 'B', 'Aircraft Drawings', 'knowledge', 'Inspection using drawings, blueprints, or system schematics.', ARRAY[10]::integer[]),
  ('AM.I.B.K4', 'general', 'B', 'Aircraft Drawings', 'knowledge', 'Terms used with aircraft drawings/blueprints.', ARRAY[10]::integer[]),
  ('AM.I.B.R1', 'general', 'B', 'Aircraft Drawings', 'risk_management', 'Interpretation of plus or minus tolerances.', ARRAY[10]::integer[]),
  ('AM.I.B.R2', 'general', 'B', 'Aircraft Drawings', 'risk_management', 'Specifications for design of alterations and repairs.', ARRAY[10]::integer[]),
  ('AM.I.B.R3', 'general', 'B', 'Aircraft Drawings', 'risk_management', 'Applicability of drawing by model and serial number.', ARRAY[10]::integer[]),
  ('AM.I.B.R4', 'general', 'B', 'Aircraft Drawings', 'risk_management', 'Identification of current version and applicability of drawing.', ARRAY[10]::integer[]),
  ('AM.I.B.S1', 'general', 'B', 'Aircraft Drawings', 'skill', 'Draw a sketch of a repair or alteration.', ARRAY[10]::integer[]),
  ('AM.I.B.S2', 'general', 'B', 'Aircraft Drawings', 'skill', 'Identify the meaning of lines and symbols.', ARRAY[10]::integer[]),
  ('AM.I.B.S3', 'general', 'B', 'Aircraft Drawings', 'skill', 'Interpret dimensions used in an aircraft drawing.', ARRAY[10]::integer[]),
  ('AM.I.B.S4', 'general', 'B', 'Aircraft Drawings', 'skill', 'Identify changes on an aircraft drawing.', ARRAY[10]::integer[]),
  ('AM.I.B.S5', 'general', 'B', 'Aircraft Drawings', 'skill', 'Determine material requirements from an aircraft drawing.', ARRAY[10]::integer[]),
  ('AM.I.B.S6', 'general', 'B', 'Aircraft Drawings', 'skill', 'Interpret graphs and charts.', ARRAY[10]::integer[]),
  ('AM.I.C.K1', 'general', 'C', 'Weight and Balance', 'knowledge', 'Weight and balance terminology.', ARRAY[5]::integer[]),
  ('AM.I.C.K2', 'general', 'C', 'Weight and Balance', 'knowledge', 'Purpose for weighing an aircraft.', ARRAY[5]::integer[]),
  ('AM.I.C.K3', 'general', 'C', 'Weight and Balance', 'knowledge', 'Weighing procedures and preparations.', ARRAY[5]::integer[]),
  ('AM.I.C.K4', 'general', 'C', 'Weight and Balance', 'knowledge', 'Calculation of arm, moment, CG, or moment index.', ARRAY[5]::integer[]),
  ('AM.I.C.K5', 'general', 'C', 'Weight and Balance', 'knowledge', 'Purpose and application of weight and CG limits.', ARRAY[5]::integer[]),
  ('AM.I.C.K6', 'general', 'C', 'Weight and Balance', 'knowledge', 'Purpose of determining CG.', ARRAY[5]::integer[]),
  ('AM.I.C.K7', 'general', 'C', 'Weight and Balance', 'knowledge', 'Adverse loading considerations.', ARRAY[5]::integer[]),
  ('AM.I.C.K8', 'general', 'C', 'Weight and Balance', 'knowledge', 'Determine proper empty weight configuration.', ARRAY[5]::integer[]),
  ('AM.I.C.K9', 'general', 'C', 'Weight and Balance', 'knowledge', 'Proper ballast placement.', ARRAY[5]::integer[]),
  ('AM.I.C.K10', 'general', 'C', 'Weight and Balance', 'knowledge', 'Jacking an aircraft.', ARRAY[4,5]::integer[]),
  ('AM.I.C.R1', 'general', 'C', 'Weight and Balance', 'risk_management', 'Situations and conditions when jacking an aircraft.', ARRAY[4]::integer[]),
  ('AM.I.C.R2', 'general', 'C', 'Weight and Balance', 'risk_management', 'Aircraft weighing procedures.', ARRAY[5]::integer[]),
  ('AM.I.C.R3', 'general', 'C', 'Weight and Balance', 'risk_management', 'Use of scales.', ARRAY[5]::integer[]),
  ('AM.I.C.R4', 'general', 'C', 'Weight and Balance', 'risk_management', 'Aerodynamic effect of CG forward or aft of limits.', ARRAY[5]::integer[]),
  ('AM.I.C.R5', 'general', 'C', 'Weight and Balance', 'risk_management', 'Aerodynamic and performance effects of weight in excess of limits.', ARRAY[5]::integer[]),
  ('AM.I.C.S1', 'general', 'C', 'Weight and Balance', 'skill', 'Research and explain procedures for weighing an aircraft.', ARRAY[5]::integer[]),
  ('AM.I.C.S2', 'general', 'C', 'Weight and Balance', 'skill', 'Perform weight and balance calculations.', ARRAY[5]::integer[]),
  ('AM.I.C.S3', 'general', 'C', 'Weight and Balance', 'skill', 'Calculate ballast weight shift and required weight location.', ARRAY[5]::integer[]),
  ('AM.I.C.S4', 'general', 'C', 'Weight and Balance', 'skill', 'Check aircraft weighing scales for calibration.', ARRAY[5]::integer[]),
  ('AM.I.C.S5', 'general', 'C', 'Weight and Balance', 'skill', 'Calculate weight and balance after equipment change.', ARRAY[5]::integer[]),
  ('AM.I.C.S6', 'general', 'C', 'Weight and Balance', 'skill', 'Compute forward and aft loaded CG limit.', ARRAY[5]::integer[]),
  ('AM.I.C.S7', 'general', 'C', 'Weight and Balance', 'skill', 'Create a maintenance record for a weight and balance change.', ARRAY[5]::integer[]),
  ('AM.I.C.S8', 'general', 'C', 'Weight and Balance', 'skill', 'Compute empty weight and empty weight CG.', ARRAY[5]::integer[]),
  ('AM.I.C.S9', 'general', 'C', 'Weight and Balance', 'skill', 'Calculate the moment of an item of equipment.', ARRAY[5]::integer[]),
  ('AM.I.C.S10', 'general', 'C', 'Weight and Balance', 'skill', 'Identify tare items.', ARRAY[5]::integer[]),
  ('AM.I.C.S11', 'general', 'C', 'Weight and Balance', 'skill', 'Locate weight and balance information.', ARRAY[5]::integer[]),
  ('AM.I.C.S12', 'general', 'C', 'Weight and Balance', 'skill', 'Locate datum.', ARRAY[5]::integer[]),
  ('AM.I.C.S13', 'general', 'C', 'Weight and Balance', 'skill', 'Locate weight and balance placarding and limitation requirements.', ARRAY[5,8]::integer[]),
  ('AM.I.C.S14', 'general', 'C', 'Weight and Balance', 'skill', 'Revise an aircraft equipment list after equipment change.', ARRAY[5]::integer[]),
  ('AM.I.C.S15', 'general', 'C', 'Weight and Balance', 'skill', 'Calculate the change needed to correct out of balance condition.', ARRAY[5]::integer[]),
  ('AM.I.C.S16', 'general', 'C', 'Weight and Balance', 'skill', 'Determine CG range using specs, TCDS, and aircraft listings.', ARRAY[5]::integer[]),
  ('AM.I.C.S17', 'general', 'C', 'Weight and Balance', 'skill', 'Calculate a weight change and complete required records.', ARRAY[5]::integer[]),
  ('AM.I.D.K1', 'general', 'D', 'Fluid Lines and Fittings', 'knowledge', 'Tubing and hose materials, applications, sizes, and fittings.', ARRAY[10]::integer[]),
  ('AM.I.D.K2', 'general', 'D', 'Fluid Lines and Fittings', 'knowledge', 'Rigid line or flexible hose material identification.', ARRAY[10]::integer[]),
  ('AM.I.D.K3', 'general', 'D', 'Fluid Lines and Fittings', 'knowledge', 'Rigid line fabrication, installation, and inspection.', ARRAY[10]::integer[]),
  ('AM.I.D.K4', 'general', 'D', 'Fluid Lines and Fittings', 'knowledge', 'Flexible hose fabrication, installation, and inspection.', ARRAY[10]::integer[]),
  ('AM.I.D.K5', 'general', 'D', 'Fluid Lines and Fittings', 'knowledge', 'Importance of torque wrench when securing fluid fittings.', ARRAY[10]::integer[]),
  ('AM.I.D.K6', 'general', 'D', 'Fluid Lines and Fittings', 'knowledge', 'Use of torque seal after installing critical fittings.', ARRAY[10]::integer[]),
  ('AM.I.D.R1', 'general', 'D', 'Fluid Lines and Fittings', 'risk_management', 'System configuration prior to and during maintenance.', ARRAY[10]::integer[]),
  ('AM.I.D.R2', 'general', 'D', 'Fluid Lines and Fittings', 'risk_management', 'Use of required safety equipment.', ARRAY[10]::integer[]),
  ('AM.I.D.R3', 'general', 'D', 'Fluid Lines and Fittings', 'risk_management', 'Hazardous fluids.', ARRAY[10]::integer[]),
  ('AM.I.D.R4', 'general', 'D', 'Fluid Lines and Fittings', 'risk_management', 'High-pressure fluid systems.', ARRAY[10,19]::integer[]),
  ('AM.I.D.R5', 'general', 'D', 'Fluid Lines and Fittings', 'risk_management', 'A twisted hose.', ARRAY[10]::integer[]),
  ('AM.I.D.R6', 'general', 'D', 'Fluid Lines and Fittings', 'risk_management', 'A loosened fitting or hose moved out of position.', ARRAY[10]::integer[]),
  ('AM.I.D.R7', 'general', 'D', 'Fluid Lines and Fittings', 'risk_management', 'Use of tools while applying torque to a fluid line.', ARRAY[10]::integer[]),
  ('AM.I.D.S1', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Fabricate a rigid line with a flare and a bend.', ARRAY[10]::integer[]),
  ('AM.I.D.S2', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Install an aircraft rigid line.', ARRAY[10]::integer[]),
  ('AM.I.D.S3', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Install an aircraft flexible hose.', ARRAY[10]::integer[]),
  ('AM.I.D.S4', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Perform a rigid line or flexible hose inspection.', ARRAY[10]::integer[]),
  ('AM.I.D.S5', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Identify installation and security requirements.', ARRAY[10]::integer[]),
  ('AM.I.D.S6', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Identify fluid lines, pneumatic lines, and fittings.', ARRAY[10]::integer[]),
  ('AM.I.D.S7', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Fabricate a flexible hose.', ARRAY[10]::integer[]),
  ('AM.I.D.S8', 'general', 'D', 'Fluid Lines and Fittings', 'skill', 'Fabricate a flareless-fitting-tube connection.', ARRAY[10]::integer[]),
  ('AM.I.E.K1', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Materials commonly used in aircraft and their general application.', ARRAY[10,29]::integer[]),
  ('AM.I.E.K2', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Heat treatment and metal working processes.', ARRAY[10,29]::integer[]),
  ('AM.I.E.K3', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Forces placed on aircraft materials.', ARRAY[10,29]::integer[]),
  ('AM.I.E.K4', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Hardware commonly used in aircraft.', ARRAY[10]::integer[]),
  ('AM.I.E.K5', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Safety wire and safety clip requirements.', ARRAY[10]::integer[]),
  ('AM.I.E.K6', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Precision measurement tools, principles, and procedures.', ARRAY[10]::integer[]),
  ('AM.I.E.K7', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Soldering preparation, types of solder, and flux usage.', ARRAY[10]::integer[]),
  ('AM.I.E.K8', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Torquing tools, principles, and procedures.', ARRAY[10]::integer[]),
  ('AM.I.E.K9', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Suitability and compatibility of materials and hardware.', ARRAY[10]::integer[]),
  ('AM.I.E.K10', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Relationship between torque and fastener preload.', ARRAY[10]::integer[]),
  ('AM.I.E.K11', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Identification markings on materials and hardware.', ARRAY[10]::integer[]),
  ('AM.I.E.K12', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Characteristics of acceptable welds.', ARRAY[10,29]::integer[]),
  ('AM.I.E.K13', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Characteristics of unacceptable welds.', ARRAY[10,29]::integer[]),
  ('AM.I.E.K14', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'knowledge', 'Procedures for weld repairs.', ARRAY[10,29]::integer[]),
  ('AM.I.E.R1', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'risk_management', 'Use of PPE.', ARRAY[10]::integer[]),
  ('AM.I.E.R2', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'risk_management', 'Improper torque.', ARRAY[10]::integer[]),
  ('AM.I.E.R3', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'risk_management', 'Used hardware or suspected unapproved parts (SUPS).', ARRAY[10]::integer[]),
  ('AM.I.E.R4', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'risk_management', 'Torquing techniques on critical fasteners.', ARRAY[10]::integer[]),
  ('AM.I.E.S1', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Install safety wire on nuts, bolts, and turnbuckles.', ARRAY[10]::integer[]),
  ('AM.I.E.S2', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Determine and properly torque aircraft hardware.', ARRAY[10]::integer[]),
  ('AM.I.E.S3', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Inspect and check welds.', ARRAY[10,29]::integer[]),
  ('AM.I.E.S4', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Identify aircraft materials and hardware by markings.', ARRAY[10]::integer[]),
  ('AM.I.E.S5', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Select and install aircraft bolts.', ARRAY[10]::integer[]),
  ('AM.I.E.S6', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Make precision measurements with Vernier scale.', ARRAY[10]::integer[]),
  ('AM.I.E.S7', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Check the concentricity of a shaft.', ARRAY[10]::integer[]),
  ('AM.I.E.S8', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Identify aircraft control cable components.', ARRAY[10,17]::integer[]),
  ('AM.I.E.S9', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Fabricate a cable assembly using a swaged-end fitting.', ARRAY[10,17]::integer[]),
  ('AM.I.E.S10', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Select the correct aluminum alloy for a structural repair.', ARRAY[10,29]::integer[]),
  ('AM.I.E.S11', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Identify rivets by physical characteristics.', ARRAY[10,29]::integer[]),
  ('AM.I.E.S12', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Determine suitability of materials for aircraft repairs.', ARRAY[10,29]::integer[]),
  ('AM.I.E.S13', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Distinguish heat-treated and non-heat-treated aluminum alloys.', ARRAY[10,29]::integer[]),
  ('AM.I.E.S14', 'general', 'E', 'Aircraft Materials, Hardware, and Processes', 'skill', 'Check for proper calibration of a micrometer.', ARRAY[10]::integer[]),
  ('AM.I.F.K1', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Aircraft towing procedures.', ARRAY[6]::integer[]),
  ('AM.I.F.K2', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Aircraft securing procedures.', ARRAY[7]::integer[]),
  ('AM.I.F.K3', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Aviation fueling/defueling procedures.', ARRAY[9,18]::integer[]),
  ('AM.I.F.K4', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Airport operation area procedures and ATC communications.', ARRAY[6]::integer[]),
  ('AM.I.F.K5', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Engine starting, ground operation, and taxiing.', ARRAY[6,42]::integer[]),
  ('AM.I.F.K6', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Types/classes of fire extinguishers and procedures.', ARRAY[16]::integer[]),
  ('AM.I.F.K7', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Aircraft oil, hydraulic, pneumatic, and deicing servicing.', ARRAY[9]::integer[]),
  ('AM.I.F.K8', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Oxygen system servicing procedures.', ARRAY[9,25]::integer[]),
  ('AM.I.F.K9', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Characteristics of aviation gasoline and turbine fuels.', ARRAY[9,18]::integer[]),
  ('AM.I.F.K10', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Fuel additives commonly used in the field.', ARRAY[9,18]::integer[]),
  ('AM.I.F.K11', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Use of approved grades/types of fuel in aircraft engines.', ARRAY[9,18]::integer[]),
  ('AM.I.F.K12', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Tool and hardware use and accountability.', ARRAY[10]::integer[]),
  ('AM.I.F.K13', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Material handling.', ARRAY[9,10]::integer[]),
  ('AM.I.F.K14', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Parts protections.', ARRAY[7,10]::integer[]),
  ('AM.I.F.K15', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Hazardous materials, SDS, and PPE.', ARRAY[10]::integer[]),
  ('AM.I.F.K16', 'general', 'F', 'Ground Operations and Servicing', 'knowledge', 'Foreign object damage effects.', ARRAY[10]::integer[]),
  ('AM.I.F.R1', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Preparing to tow an aircraft.', ARRAY[6]::integer[]),
  ('AM.I.F.R2', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Connecting external power equipment.', ARRAY[14]::integer[]),
  ('AM.I.F.R3', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Fueling/defueling ungrounded aircraft.', ARRAY[9,18]::integer[]),
  ('AM.I.F.R4', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Misfueling and incorrect/contaminated fuel.', ARRAY[9,18]::integer[]),
  ('AM.I.F.R5', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Oxygen system servicing.', ARRAY[9,25]::integer[]),
  ('AM.I.F.R6', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Engine start/run-up without using a checklist.', ARRAY[42]::integer[]),
  ('AM.I.F.R7', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Engine starting and ground operations.', ARRAY[42]::integer[]),
  ('AM.I.F.R8', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Engine starting while troubleshooting/adjusting controls.', ARRAY[42,47]::integer[]),
  ('AM.I.F.R9', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Ground operation with cowling removed contrary to instructions.', ARRAY[42]::integer[]),
  ('AM.I.F.R10', 'general', 'F', 'Ground Operations and Servicing', 'risk_management', 'Ground operation near other aircraft or equipment.', ARRAY[6]::integer[]),
  ('AM.I.F.S1', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Perform a FOD control procedure.', ARRAY[10]::integer[]),
  ('AM.I.F.S2', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Connect external power to an aircraft.', ARRAY[14]::integer[]),
  ('AM.I.F.S3', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Prepare an aircraft for towing.', ARRAY[6]::integer[]),
  ('AM.I.F.S4', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Use appropriate hand signals for aircraft movement.', ARRAY[6]::integer[]),
  ('AM.I.F.S5', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Inspect fuel system for water and FOD contamination.', ARRAY[9,18]::integer[]),
  ('AM.I.F.S6', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Identify different grades of aviation fuel.', ARRAY[9,18]::integer[]),
  ('AM.I.F.S7', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Select an approved fuel for an aircraft.', ARRAY[9,18]::integer[]),
  ('AM.I.F.S8', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Prepare an aircraft for fueling.', ARRAY[9,18]::integer[]),
  ('AM.I.F.S9', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Follow a checklist to start or shut down an engine.', ARRAY[42]::integer[]),
  ('AM.I.F.S10', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Identify procedures for extinguishing induction fires.', ARRAY[16,42]::integer[]),
  ('AM.I.F.S11', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Secure an aircraft.', ARRAY[7]::integer[]),
  ('AM.I.F.S12', 'general', 'F', 'Ground Operations and Servicing', 'skill', 'Locate procedures for securing turbine aircraft after shutdown.', ARRAY[7,42]::integer[]),
  ('AM.I.G.K1', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Aircraft cleaning procedures.', ARRAY[9,29]::integer[]),
  ('AM.I.G.K2', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Corrosion theory and causation.', ARRAY[29]::integer[]),
  ('AM.I.G.K3', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Types and effects of corrosion.', ARRAY[29]::integer[]),
  ('AM.I.G.K4', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Corrosion-prone areas in aircraft.', ARRAY[29]::integer[]),
  ('AM.I.G.K5', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Corrosion preventive maintenance procedures.', ARRAY[29]::integer[]),
  ('AM.I.G.K6', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Corrosion identification and inspection.', ARRAY[29]::integer[]),
  ('AM.I.G.K7', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Corrosion removal and treatment procedures.', ARRAY[29]::integer[]),
  ('AM.I.G.K8', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Corrosion preventive compounds (CPC).', ARRAY[29]::integer[]),
  ('AM.I.G.K9', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Selection of optimal CPC and frequency of treatment.', ARRAY[29]::integer[]),
  ('AM.I.G.K10', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Use of high-pressure application equipment.', ARRAY[29]::integer[]),
  ('AM.I.G.K11', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Improper use of cleaners on aluminum or composite.', ARRAY[29]::integer[]),
  ('AM.I.G.K12', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Dissimilar metals causing accelerated corrosion.', ARRAY[10,29]::integer[]),
  ('AM.I.G.K13', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Conversion coatings.', ARRAY[29]::integer[]),
  ('AM.I.G.K14', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Materials used for protection of airframe structures.', ARRAY[29]::integer[]),
  ('AM.I.G.K15', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Primer materials.', ARRAY[29]::integer[]),
  ('AM.I.G.K16', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Topcoat materials.', ARRAY[29]::integer[]),
  ('AM.I.G.K17', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Surface preparation for a desired finishing material.', ARRAY[29]::integer[]),
  ('AM.I.G.K18', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Effects of ambient conditions on finishing materials.', ARRAY[29]::integer[]),
  ('AM.I.G.K19', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Effects of improper surface preparation.', ARRAY[29]::integer[]),
  ('AM.I.G.K20', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Regulatory requirements for replacing ID/registration markings.', ARRAY[8]::integer[]),
  ('AM.I.G.K21', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Inspection of aircraft finishes.', ARRAY[29]::integer[]),
  ('AM.I.G.K22', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Safety practices when using finishing materials.', ARRAY[29]::integer[]),
  ('AM.I.G.K23', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Finishing materials application techniques.', ARRAY[29]::integer[]),
  ('AM.I.G.K24', 'general', 'G', 'Cleaning and Corrosion Control', 'knowledge', 'Control surface balance considerations after refinishing.', ARRAY[17,29]::integer[]),
  ('AM.I.G.R1', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'Health concerns when using paints, solvents, finishing materials.', ARRAY[29]::integer[]),
  ('AM.I.G.R2', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'Ventilation.', ARRAY[29]::integer[]),
  ('AM.I.G.R3', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'Identification of materials for cleaning/corrosion treatment.', ARRAY[29]::integer[]),
  ('AM.I.G.R4', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'SDS PPE instructions for corrosion removal/treatment.', ARRAY[29]::integer[]),
  ('AM.I.G.R5', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'Working with flammable chemicals.', ARRAY[29]::integer[]),
  ('AM.I.G.R6', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'Disposal of chemicals and waste materials.', ARRAY[29]::integer[]),
  ('AM.I.G.R7', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'Use of PPE when working with paints and solvents.', ARRAY[29]::integer[]),
  ('AM.I.G.R8', 'general', 'G', 'Cleaning and Corrosion Control', 'risk_management', 'Application of finishing materials.', ARRAY[29]::integer[]),
  ('AM.I.G.S1', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Perform a portion of an aircraft corrosion inspection.', ARRAY[29]::integer[]),
  ('AM.I.G.S2', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Identify, select, and use corrosion prevention/cleaning materials.', ARRAY[29]::integer[]),
  ('AM.I.G.S3', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Apply corrosion prevention/coating materials.', ARRAY[29]::integer[]),
  ('AM.I.G.S4', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Inspect finishes and identify defects.', ARRAY[29]::integer[]),
  ('AM.I.G.S5', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Inspect an aircraft compartment for corrosion.', ARRAY[29]::integer[]),
  ('AM.I.G.S6', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Identify procedures to clean and protect plastics.', ARRAY[29,34]::integer[]),
  ('AM.I.G.S7', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Determine location and size requirements for registration numbers.', ARRAY[8]::integer[]),
  ('AM.I.G.S8', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Prepare composite surface for painting.', ARRAY[29]::integer[]),
  ('AM.I.G.S9', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Identify finishing materials and appropriate thinners.', ARRAY[29]::integer[]),
  ('AM.I.G.S10', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Layout and mask a surface for painting.', ARRAY[29]::integer[]),
  ('AM.I.G.S11', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Prepare metal surface for painting.', ARRAY[29]::integer[]),
  ('AM.I.G.S12', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Determine what paint system can be used on a given aircraft.', ARRAY[29]::integer[]),
  ('AM.I.G.S13', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Apply etch solution and conversion coating.', ARRAY[29]::integer[]),
  ('AM.I.G.S14', 'general', 'G', 'Cleaning and Corrosion Control', 'skill', 'Identify types of protective finishes.', ARRAY[29]::integer[]),
  ('AM.I.H.K1-K13', 'general', 'H', 'Mathematics', 'knowledge', 'All mathematics elements (areas, volumes, geometry, ratios, algebra, etc.).', ARRAY[1]::integer[]),
  ('AM.I.H.R1-R3', 'general', 'H', 'Mathematics', 'risk_management', 'All math risk elements (order of operations, integers, rounding).', ARRAY[1]::integer[]),
  ('AM.I.H.S1-S8', 'general', 'H', 'Mathematics', 'skill', 'All math skill elements (square root, volume, area, conversions, etc.).', ARRAY[1]::integer[]),
  ('AM.I.I.K1-K23', 'general', 'I', 'Regulations, Maintenance Forms, Records, and Publications', 'knowledge', 'All regulatory knowledge elements (privileges, records, forms, ADs, publications, etc.).', ARRAY[2]::integer[]),
  ('AM.I.I.R1-R5', 'general', 'I', 'Regulations, Maintenance Forms, Records, and Publications', 'risk_management', 'All regulatory risk elements (documentation, SDS, complacency, warnings, applicability).', ARRAY[2]::integer[]),
  ('AM.I.I.S1-S18', 'general', 'I', 'Regulations, Maintenance Forms, Records, and Publications', 'skill', 'All regulatory skill elements (Form 337, AD compliance, records, TCDS, etc.).', ARRAY[2]::integer[]),
  ('AM.I.J.K1-K13', 'general', 'J', 'Physics for Aviation', 'knowledge', 'All physics elements (matter, energy, Bernoulli''s, Newton''s, aerodynamics, etc.).', ARRAY[1]::integer[]),
  ('AM.I.J.R1-R4', 'general', 'J', 'Physics for Aviation', 'risk_management', 'All physics risk elements (density altitude, repair effects, testing data, units).', ARRAY[1]::integer[]),
  ('AM.I.J.S1-S8', 'general', 'J', 'Physics for Aviation', 'skill', 'All physics skill elements (temp conversion, density alt, pressure, horsepower).', ARRAY[1]::integer[]),
  ('AM.I.K.K1-K5', 'general', 'K', 'Inspection Concepts and Techniques', 'knowledge', 'All inspection knowledge (measuring tools, calibration, NDT, inspection programs).', ARRAY[2,10]::integer[]),
  ('AM.I.K.R1-R5', 'general', 'K', 'Inspection Concepts and Techniques', 'risk_management', 'All inspection risk elements (demagnetizing, precision instruments, calibration, etc.).', ARRAY[2,10]::integer[]),
  ('AM.I.K.S1-S8', 'general', 'K', 'Inspection Concepts and Techniques', 'skill', 'All inspection skill elements (calipers, micrometers, dye penetrant, NDT, AD compliance).', ARRAY[2,10]::integer[]),
  ('AM.I.L.K1-K11', 'general', 'L', 'Human Factors', 'knowledge', 'All human factors knowledge (safety culture, human error, communication, etc.).', ARRAY[1]::integer[]),
  ('AM.I.L.R1-R3', 'general', 'L', 'Human Factors', 'risk_management', 'All human factors risk elements (hazard reporting, fatigue, condition monitoring).', ARRAY[1]::integer[]),
  ('AM.I.L.S1-S3', 'general', 'L', 'Human Factors', 'skill', 'All human factors skill elements (defect report, shift turnover, HF errors).', ARRAY[1]::integer[]),
  ('AM.II.A.K1-K17', 'airframe', 'A', 'Metallic Structures', 'knowledge', 'All metallic structures knowledge (inspection, defects, materials, rivets, welding, etc.).', ARRAY[29,31,33,35]::integer[]),
  ('AM.II.A.R1-R5', 'airframe', 'A', 'Metallic Structures', 'risk_management', 'All metallic structures risk elements (material selection, safety, PPE, welding).', ARRAY[29]::integer[]),
  ('AM.II.A.S1-S14', 'airframe', 'A', 'Metallic Structures', 'skill', 'All metallic structures skills (rivets, sheet metal repair, fasteners, fabrication).', ARRAY[29,31,33,35]::integer[]),
  ('AM.II.B.K1-K6', 'airframe', 'B', 'Non-Metallic Structures', 'knowledge', 'Wood structures knowledge (inspection, types, defects, repair).', ARRAY[29]::integer[]),
  ('AM.II.B.K7-K17', 'airframe', 'B', 'Non-Metallic Structures', 'knowledge', 'Fabric covering knowledge (types, seams, attachment, inspection, repair).', ARRAY[29]::integer[]),
  ('AM.II.B.K18-K22', 'airframe', 'B', 'Non-Metallic Structures', 'knowledge', 'Composite structures knowledge (inspection, defects, materials, repair).', ARRAY[29]::integer[]),
  ('AM.II.B.K23-K25', 'airframe', 'B', 'Non-Metallic Structures', 'knowledge', 'Thermoplastic material knowledge (inspection, storage, installation).', ARRAY[29,34]::integer[]),
  ('AM.II.B.K26-K27', 'airframe', 'B', 'Non-Metallic Structures', 'knowledge', 'Window care, maintenance, temporary and permanent repairs.', ARRAY[34]::integer[]),
  ('AM.II.B.K28-K29', 'airframe', 'B', 'Non-Metallic Structures', 'knowledge', 'Safety practices for composites/windows; restraints and upholstery.', ARRAY[15,29,34]::integer[]),
  ('AM.II.B.R1-R7', 'airframe', 'B', 'Non-Metallic Structures', 'risk_management', 'All non-metallic risk elements (adhesives, composites, shelf life, materials).', ARRAY[29]::integer[]),
  ('AM.II.B.S1-S12', 'airframe', 'B', 'Non-Metallic Structures', 'skill', 'All non-metallic skills (composite repair, fiberglass, windshields, vacuum bag).', ARRAY[29,34]::integer[]),
  ('AM.II.C.K1-K13', 'airframe', 'C', 'Flight Controls', 'knowledge', 'All flight controls knowledge (cables, stops, rigging, balance, surfaces).', ARRAY[17]::integer[]),
  ('AM.II.C.R1-R5', 'airframe', 'C', 'Flight Controls', 'risk_management', 'All flight controls risk elements (cable tension, rigging, lifting equipment, calibration).', ARRAY[17]::integer[]),
  ('AM.II.C.S1-S13', 'airframe', 'C', 'Flight Controls', 'skill', 'All flight controls skills (rigging, inspection, cable adjustment, balance, fabrication).', ARRAY[17]::integer[]),
  ('AM.II.D.K1-K9', 'airframe', 'D', 'Airframe Inspection', 'knowledge', 'All airframe inspection knowledge (14 CFR parts 43/91, ADs, life-limited parts).', ARRAY[2]::integer[]),
  ('AM.II.D.R1-R5', 'airframe', 'D', 'Airframe Inspection', 'risk_management', 'All airframe inspection risk elements (interpretation, visual inspection, radiographic).', ARRAY[2]::integer[]),
  ('AM.II.D.S1-S7', 'airframe', 'D', 'Airframe Inspection', 'skill', 'All airframe inspection skills (100-hr inspection, records, AD compliance, seatbelts).', ARRAY[2,15]::integer[]),
  ('AM.II.E.K1-K13', 'airframe', 'E', 'Landing Gear Systems', 'knowledge', 'All landing gear knowledge (fixed/retractable, struts, brakes, tires, steering).', ARRAY[22]::integer[]),
  ('AM.II.E.R1-R6', 'airframe', 'E', 'Landing Gear Systems', 'risk_management', 'All landing gear risk elements (jacks, high pressure, hydraulic fluids, operations).', ARRAY[22]::integer[]),
  ('AM.II.E.S1-S29', 'airframe', 'E', 'Landing Gear Systems', 'skill', 'All landing gear skills (service, inspect, troubleshoot, brakes, tires, steering, etc.).', ARRAY[22]::integer[]),
  ('AM.II.F.K1-K11', 'airframe', 'F', 'Hydraulic and Pneumatic Systems', 'knowledge', 'All hydraulic/pneumatic knowledge (components, fluids, seals, accumulators, filters).', ARRAY[19,26]::integer[]),
  ('AM.II.F.R1-R5', 'airframe', 'F', 'Hydraulic and Pneumatic Systems', 'risk_management', 'All hydraulic/pneumatic risk elements (pressure relief, storage, cross-contamination).', ARRAY[19,26]::integer[]),
  ('AM.II.F.S1-S16', 'airframe', 'F', 'Hydraulic and Pneumatic Systems', 'skill', 'All hydraulic/pneumatic skills (identify fluids, seals, service, troubleshoot, etc.).', ARRAY[19,26]::integer[]),
  ('AM.II.G.K1-K3', 'airframe', 'G', 'Environmental Systems', 'knowledge', 'Pressurization, bleed air heating, instrument cooling.', ARRAY[11]::integer[]),
  ('AM.II.G.K4-K5', 'airframe', 'G', 'Environmental Systems', 'knowledge', 'Exhaust heat exchanger and combustion heater systems.', ARRAY[11]::integer[]),
  ('AM.II.G.K6-K8', 'airframe', 'G', 'Environmental Systems', 'knowledge', 'Vapor-cycle, air-cycle, and cabin pressurization systems.', ARRAY[11]::integer[]),
  ('AM.II.G.K9-K10', 'airframe', 'G', 'Environmental Systems', 'knowledge', 'Oxygen systems types, components, maintenance, and inspection.', ARRAY[25]::integer[]),
  ('AM.II.G.R1', 'airframe', 'G', 'Environmental Systems', 'risk_management', 'Oxygen system maintenance.', ARRAY[25]::integer[]),
  ('AM.II.G.R2', 'airframe', 'G', 'Environmental Systems', 'risk_management', 'Recovery of vapor-cycle refrigerant.', ARRAY[11]::integer[]),
  ('AM.II.G.R3', 'airframe', 'G', 'Environmental Systems', 'risk_management', 'Handling chemical oxygen generating systems.', ARRAY[25]::integer[]),
  ('AM.II.G.R4', 'airframe', 'G', 'Environmental Systems', 'risk_management', 'Storage, handling, and use of compressed gas cylinders.', ARRAY[25]::integer[]),
  ('AM.II.G.R5', 'airframe', 'G', 'Environmental Systems', 'risk_management', 'Manufacturer''s recommended servicing procedures, refrigerant types.', ARRAY[11]::integer[]),
  ('AM.II.G.R6', 'airframe', 'G', 'Environmental Systems', 'risk_management', 'Maintenance of combustion heaters.', ARRAY[11]::integer[]),
  ('AM.II.G.S1-S7', 'airframe', 'G', 'Environmental Systems', 'skill', 'Oxygen system skills (inspect, purge, service, masks, regulators, chemical generators).', ARRAY[25]::integer[]),
  ('AM.II.G.S8-S15', 'airframe', 'G', 'Environmental Systems', 'skill', 'HVAC/pressurization skills (combustion heater, refrigerant, air-cycle, outflow valve).', ARRAY[11]::integer[]),
  ('AM.II.H.K1-K24', 'airframe', 'H', 'Aircraft Instrument Systems', 'knowledge', 'All instrument knowledge (annunciators, compass, pitot-static, gyros, EFIS, etc.).', ARRAY[21,24]::integer[]),
  ('AM.II.H.R1-R5', 'airframe', 'H', 'Aircraft Instrument Systems', 'risk_management', 'All instrument risk elements (pressurized air, annunciators, ESD, gyros, pitot-static).', ARRAY[21,24]::integer[]),
  ('AM.II.H.S1-S14', 'airframe', 'H', 'Aircraft Instrument Systems', 'skill', 'All instrument skills (static test, install, range marks, compass, vacuum, stall warning).', ARRAY[21,24]::integer[]),
  ('AM.II.I.K1-K6', 'airframe', 'I', 'Communications and Navigation Systems', 'knowledge', 'Radio/comm knowledge (principles, components, antennas, VHF/HF, SATCOM, ACARS).', ARRAY[13]::integer[]),
  ('AM.II.I.K7', 'airframe', 'I', 'Communications and Navigation Systems', 'knowledge', 'Emergency locator transmitter (ELT).', ARRAY[13]::integer[]),
  ('AM.II.I.K8-K15', 'airframe', 'I', 'Communications and Navigation Systems', 'knowledge', 'Navigation systems (ADF, VOR, DME, ILS, GPS, TCAS, weather radar, GPWS).', ARRAY[24]::integer[]),
  ('AM.II.I.K16-K18', 'airframe', 'I', 'Communications and Navigation Systems', 'knowledge', 'Autopilot, auto-throttle, and stability augmentation systems.', ARRAY[12]::integer[]),
  ('AM.II.I.K19-K21', 'airframe', 'I', 'Communications and Navigation Systems', 'knowledge', 'Radio altimeter, ADS-B, transponder/encoder.', ARRAY[24]::integer[]),
  ('AM.II.I.R1-R6', 'airframe', 'I', 'Communications and Navigation Systems', 'risk_management', 'All comm/nav risk elements (ELT testing, high power, wire routing, antennas, ESD).', ARRAY[13,24]::integer[]),
  ('AM.II.I.S1-S13', 'airframe', 'I', 'Communications and Navigation Systems', 'skill', 'All comm/nav skills (placards, autopilot, antennas, VHF, ELT, coaxial cable, etc.).', ARRAY[12,13,24]::integer[]),
  ('AM.II.J.K1-K9', 'airframe', 'J', 'Aircraft Fuel Systems', 'knowledge', 'All fuel system knowledge (types, components, tanks, transfer, jettison, quantity).', ARRAY[18]::integer[]),
  ('AM.II.J.R1-R5', 'airframe', 'J', 'Aircraft Fuel Systems', 'risk_management', 'All fuel system risk elements (maintenance, contamination, spills, tank entry, defueling).', ARRAY[18]::integer[]),
  ('AM.II.J.S1-S18', 'airframe', 'J', 'Aircraft Fuel Systems', 'skill', 'All fuel system skills (inspect, troubleshoot, valves, strainer, quantity, defueling, etc.).', ARRAY[18]::integer[]),
  ('AM.II.K.K1-K17', 'airframe', 'K', 'Aircraft Electrical Systems', 'knowledge', 'All airframe electrical knowledge (generators, alternators, wiring, lighting, CSD/IDG).', ARRAY[14,23]::integer[]),
  ('AM.II.K.R1-R9', 'airframe', 'K', 'Aircraft Electrical Systems', 'risk_management', 'All airframe electrical risk elements (testing, external power, energized circuits, wiring, soldering).', ARRAY[14]::integer[]),
  ('AM.II.K.S1-S20', 'airframe', 'K', 'Aircraft Electrical Systems', 'skill', 'All airframe electrical skills (wiring, connectors, solder, troubleshoot, lights, bonding).', ARRAY[14,23]::integer[]),
  ('AM.II.L.K1-K7', 'airframe', 'L', 'Ice and Rain Control Systems', 'knowledge', 'All ice/rain knowledge (icing causes, detection, anti-ice, de-ice, wipers, rain systems).', ARRAY[20]::integer[]),
  ('AM.II.L.R1-R3', 'airframe', 'L', 'Ice and Rain Control Systems', 'risk_management', 'All ice/rain risk elements (system testing, deicing fluids, cleaning heated windshields).', ARRAY[20]::integer[]),
  ('AM.II.L.S1-S9', 'airframe', 'L', 'Ice and Rain Control Systems', 'skill', 'All ice/rain skills (pitot heat, deicer boots, windshield heat, wipers, thermal anti-ice).', ARRAY[20]::integer[]),
  ('AM.II.M.K1-K7', 'airframe', 'M', 'Airframe Fire Protection Systems', 'knowledge', 'All fire protection knowledge (fire types/zones, detection, smoke/CO, extinguishing).', ARRAY[16]::integer[]),
  ('AM.II.M.R1-R3', 'airframe', 'M', 'Airframe Fire Protection Systems', 'risk_management', 'All fire protection risk elements (squibs, PPE, extinguishing agents).', ARRAY[16]::integer[]),
  ('AM.II.M.S1-S12', 'airframe', 'M', 'Airframe Fire Protection Systems', 'skill', 'All fire protection skills (troubleshoot, inspect, smoke detection, continuous loop, etc.).', ARRAY[16]::integer[]),
  ('AM.II.N.K1-K9', 'airframe', 'N', 'Rotorcraft Fundamentals', 'knowledge', 'All rotorcraft knowledge (aerodynamics, controls, transmissions, rotor systems).', ARRAY[37,38,39,40]::integer[]),
  ('AM.II.N.R1-R4', 'airframe', 'N', 'Rotorcraft Fundamentals', 'risk_management', 'All rotorcraft risk elements (blade safety, ground handling, functional tests, maintenance).', ARRAY[37,38,39,40]::integer[]),
  ('AM.II.N.S1-S4', 'airframe', 'N', 'Rotorcraft Fundamentals', 'skill', 'All rotorcraft skills (components, track/balance, rigging, control procedures).', ARRAY[37,38,39,40]::integer[]),
  ('AM.II.O.K1-K3', 'airframe', 'O', 'Water and Waste Systems', 'knowledge', 'All water/waste knowledge (potable water, lavatory waste, servicing).', ARRAY[27]::integer[]),
  ('AM.II.O.R1', 'airframe', 'O', 'Water and Waste Systems', 'risk_management', 'Servicing lavatory waste systems, safety equipment.', ARRAY[27]::integer[]),
  ('AM.II.O.S1-S2', 'airframe', 'O', 'Water and Waste Systems', 'skill', 'All water/waste skills (lavatory servicing, potable water servicing).', ARRAY[27]::integer[]),
  ('AM.III.A.K1-K14', 'powerplant', 'A', 'Reciprocating Engines', 'knowledge', 'All reciprocating engine knowledge (theory, components, induction, cooling, lubrication, ignition).', ARRAY[42,43,44,45,46,47,48,50]::integer[]),
  ('AM.III.A.R1-R6', 'powerplant', 'A', 'Reciprocating Engines', 'risk_management', 'All reciprocating engine risk elements (prop strikes, hot sections, ignition, detonation, preignition).', ARRAY[42,43,45]::integer[]),
  ('AM.III.A.S1-S16', 'powerplant', 'A', 'Reciprocating Engines', 'skill', 'All reciprocating engine skills (compression test, timing, magnetos, troubleshooting, borescope).', ARRAY[42,43,44,45,46,47,48]::integer[]),
  ('AM.III.B.K1-K16', 'powerplant', 'B', 'Turbine Engines', 'knowledge', 'All turbine engine knowledge (theory, compressors, turbines, hot section, FADEC, APU).', ARRAY[28,41,42,43,44,45,46,47,48,50]::integer[]),
  ('AM.III.B.R1-R6', 'powerplant', 'B', 'Turbine Engines', 'risk_management', 'All turbine engine risk elements (FOD, hot section, borescope, FADEC, high temps).', ARRAY[41,42,43,44,45,46,47]::integer[]),
  ('AM.III.B.S1-S14', 'powerplant', 'B', 'Turbine Engines', 'skill', 'All turbine engine skills (borescope, trim, rigging, troubleshooting, vibration, APU).', ARRAY[28,41,42,43,44,45,46,47,48,50]::integer[]),
  ('AM.III.C.K1-K10', 'powerplant', 'C', 'Engine Inspection', 'knowledge', 'All engine inspection knowledge (100-hr, annual, borescope, ADs, SBs, TBO, records).', ARRAY[2,42,43,44,45,46,47,48]::integer[]),
  ('AM.III.C.R1-R4', 'powerplant', 'C', 'Engine Inspection', 'risk_management', 'All engine inspection risk elements (hot section, prop strike, oil contamination, torque).', ARRAY[2,42,43]::integer[]),
  ('AM.III.C.S1-S10', 'powerplant', 'C', 'Engine Inspection', 'skill', 'All engine inspection skills (compression test, borescope, oil filter, chip detector, ADs).', ARRAY[2,42,43,44,45,46,47]::integer[]),
  ('AM.III.D.K1-K14', 'powerplant', 'D', 'Engine Instrument Systems', 'knowledge', 'All engine instrument knowledge (tach, MAP, EGT, CHT, oil temp/pressure, vibration, FADEC).', ARRAY[48]::integer[]),
  ('AM.III.D.R1-R3', 'powerplant', 'D', 'Engine Instrument Systems', 'risk_management', 'All engine instrument risk elements (sensor handling, wiring, calibration).', ARRAY[48]::integer[]),
  ('AM.III.D.S1-S6', 'powerplant', 'D', 'Engine Instrument Systems', 'skill', 'All engine instrument skills (install, troubleshoot, verify indications, wiring).', ARRAY[48]::integer[]),
  ('AM.III.E.K1-K12', 'powerplant', 'E', 'Engine Fire Protection Systems', 'knowledge', 'All engine fire protection knowledge (detection, extinguishing, loops, bottles, squibs).', ARRAY[16]::integer[]),
  ('AM.III.E.R1-R3', 'powerplant', 'E', 'Engine Fire Protection Systems', 'risk_management', 'All engine fire protection risk elements (bottle handling, squibs, leaks).', ARRAY[16]::integer[]),
  ('AM.III.E.S1-S7', 'powerplant', 'E', 'Engine Fire Protection Systems', 'skill', 'All engine fire protection skills (inspect, test loops, troubleshoot, replace bottles).', ARRAY[16]::integer[]),
  ('AM.III.F.K1-K13', 'powerplant', 'F', 'Engine Electrical Systems', 'knowledge', 'All engine electrical knowledge (starters, generators, alternators, ignition, FADEC).', ARRAY[14,45,48]::integer[]),
  ('AM.III.F.R1-R4', 'powerplant', 'F', 'Engine Electrical Systems', 'risk_management', 'All engine electrical risk elements (high voltage, magnetos, wiring, bonding).', ARRAY[14,45]::integer[]),
  ('AM.III.F.S1-S12', 'powerplant', 'F', 'Engine Electrical Systems', 'skill', 'All engine electrical skills (timing, magnetos, leads, spark plugs, troubleshooting).', ARRAY[14,45,48]::integer[]),
  ('AM.III.G.K1-K14', 'powerplant', 'G', 'Lubrication Systems', 'knowledge', 'All lubrication knowledge (wet/dry sump, pumps, filters, coolers, oil types).', ARRAY[50]::integer[]),
  ('AM.III.G.R1-R3', 'powerplant', 'G', 'Lubrication Systems', 'risk_management', 'All lubrication risk elements (contamination, servicing, leaks).', ARRAY[50]::integer[]),
  ('AM.III.G.S1-S10', 'powerplant', 'G', 'Lubrication Systems', 'skill', 'All lubrication skills (service, inspect, troubleshoot, filter, chip detector).', ARRAY[50]::integer[]),
  ('AM.III.H.K1-K12', 'powerplant', 'H', 'Ignition and Starting Systems', 'knowledge', 'All ignition/starting knowledge (magnetos, ignition harness, spark plugs, starters).', ARRAY[45]::integer[]),
  ('AM.III.H.R1-R3', 'powerplant', 'H', 'Ignition and Starting Systems', 'risk_management', 'All ignition/starting risk elements (high voltage, timing, hot mags).', ARRAY[45]::integer[]),
  ('AM.III.H.S1-S10', 'powerplant', 'H', 'Ignition and Starting Systems', 'skill', 'All ignition/starting skills (time magnetos, inspect plugs, troubleshoot, leads).', ARRAY[45]::integer[]),
  ('AM.III.I.K1-K18', 'powerplant', 'I', 'Fuel Metering Systems', 'knowledge', 'All fuel metering knowledge (carburetors, injection, FADEC, fuel controls, governors).', ARRAY[44]::integer[]),
  ('AM.III.I.R1-R4', 'powerplant', 'I', 'Fuel Metering Systems', 'risk_management', 'All fuel metering risk elements (fuel contamination, mixture, leaks, adjustments).', ARRAY[44]::integer[]),
  ('AM.III.I.S1-S14', 'powerplant', 'I', 'Fuel Metering Systems', 'skill', 'All fuel metering skills (carburetor, injection, mixture, idle, troubleshooting).', ARRAY[44]::integer[]),
  ('AM.III.J.K1-K11', 'powerplant', 'J', 'Induction and Engine Airflow Systems', 'knowledge', 'All induction knowledge (air filters, alternate air, turbocharging, supercharging).', ARRAY[42,46]::integer[]),
  ('AM.III.J.R1-R3', 'powerplant', 'J', 'Induction and Engine Airflow Systems', 'risk_management', 'All induction risk elements (icing, turbocharger overspeed, leaks).', ARRAY[42,46]::integer[]),
  ('AM.III.J.S1-S10', 'powerplant', 'J', 'Induction and Engine Airflow Systems', 'skill', 'All induction skills (inspect, troubleshoot, turbocharger, wastegate, alternate air).', ARRAY[42,46]::integer[]),
  ('AM.III.K.K1-K13', 'powerplant', 'K', 'Engine Cooling Systems', 'knowledge', 'All cooling knowledge (air cooling, baffles, cowl flaps, liquid cooling, heat exchangers).', ARRAY[42]::integer[]),
  ('AM.III.K.R1-R3', 'powerplant', 'K', 'Engine Cooling Systems', 'risk_management', 'All cooling risk elements (overheating, cowl flap misrigging, airflow obstructions).', ARRAY[42]::integer[]),
  ('AM.III.K.S1-S8', 'powerplant', 'K', 'Engine Cooling Systems', 'skill', 'All cooling skills (inspect baffles, troubleshoot overheating, adjust cowl flaps).', ARRAY[42]::integer[]),
  ('AM.III.L.K1-K10', 'powerplant', 'L', 'Engine Exhaust and Reverser Systems', 'knowledge', 'All exhaust knowledge (manifolds, mufflers, heat exchangers, thrust reversers).', ARRAY[49]::integer[]),
  ('AM.III.L.R1-R3', 'powerplant', 'L', 'Engine Exhaust and Reverser Systems', 'risk_management', 'All exhaust risk elements (CO hazards, cracks, hot spots, reverser deployment).', ARRAY[49]::integer[]),
  ('AM.III.L.S1-S9', 'powerplant', 'L', 'Engine Exhaust and Reverser Systems', 'skill', 'All exhaust skills (inspect, troubleshoot, CO checks, reverser operation).', ARRAY[49]::integer[]),
  ('AM.III.M.K1-K12', 'powerplant', 'M', 'Propellers', 'knowledge', 'All propeller knowledge (fixed pitch, constant speed, feathering, governors, ice control).', ARRAY[36]::integer[]),
  ('AM.III.M.R1-R4', 'powerplant', 'M', 'Propellers', 'risk_management', 'All propeller risk elements (blade angle, overspeed, leaks, feathering hazards).', ARRAY[36]::integer[]),
  ('AM.III.M.S1-S14', 'powerplant', 'M', 'Propellers', 'skill', 'All propeller skills (track, balance, governor, feathering, deice, troubleshooting).', ARRAY[36]::integer[]),
  ('AM.III.N.K1-K12', 'powerplant', 'N', 'Engine Fuel Systems', 'knowledge', 'All engine fuel system knowledge (boost pumps, selectors, strainers, valves, contamination).', ARRAY[44]::integer[]),
  ('AM.III.N.R1-R3', 'powerplant', 'N', 'Engine Fuel Systems', 'risk_management', 'All engine fuel system risk elements (fuel contamination, leaks, misfueling).', ARRAY[44]::integer[]),
  ('AM.III.N.S1-S10', 'powerplant', 'N', 'Engine Fuel Systems', 'skill', 'All engine fuel system skills (inspect, troubleshoot, strainers, selectors, boost pumps).', ARRAY[44]::integer[]),
  ('AM.III.O.K1-K10', 'powerplant', 'O', 'Engine Induction and Airflow Systems', 'knowledge', 'All induction/airflow knowledge (filters, alternate air, turbocharging, intercoolers).', ARRAY[42,46]::integer[]),
  ('AM.III.O.R1-R3', 'powerplant', 'O', 'Engine Induction and Airflow Systems', 'risk_management', 'All induction/airflow risk elements (icing, leaks, turbo overspeed).', ARRAY[42,46]::integer[]),
  ('AM.III.O.S1-S8', 'powerplant', 'O', 'Engine Induction and Airflow Systems', 'skill', 'All induction/airflow skills (inspect, troubleshoot, turbocharger, wastegate).', ARRAY[42,46]::integer[]),
  ('AM.III.P.K1-K11', 'powerplant', 'P', 'Engine Cooling Systems', 'knowledge', 'All cooling knowledge (air cooling, liquid cooling, baffles, cowl flaps, heat exchangers).', ARRAY[42]::integer[]),
  ('AM.III.P.R1-R3', 'powerplant', 'P', 'Engine Cooling Systems', 'risk_management', 'All cooling risk elements (overheating, airflow obstructions, misrigging).', ARRAY[42]::integer[]),
  ('AM.III.P.S1-S7', 'powerplant', 'P', 'Engine Cooling Systems', 'skill', 'All cooling skills (inspect baffles, troubleshoot overheating, adjust cowl flaps).', ARRAY[42]::integer[]),
  ('AM.III.Q.K1-K9', 'powerplant', 'Q', 'Engine Exhaust Systems', 'knowledge', 'All exhaust knowledge (manifolds, mufflers, heat exchangers, turbo components).', ARRAY[49]::integer[]),
  ('AM.III.Q.R1-R3', 'powerplant', 'Q', 'Engine Exhaust Systems', 'risk_management', 'All exhaust risk elements (CO hazards, cracks, hot spots).', ARRAY[49]::integer[]),
  ('AM.III.Q.S1-S8', 'powerplant', 'Q', 'Engine Exhaust Systems', 'skill', 'All exhaust skills (inspect, troubleshoot, CO checks, leak detection).', ARRAY[49]::integer[]),
  ('AM.III.R.K1-K12', 'powerplant', 'R', 'Engine Starting Systems', 'knowledge', 'All starting system knowledge (electric, pneumatic, starter-generators, igniters).', ARRAY[45,51]::integer[]),
  ('AM.III.R.R1-R3', 'powerplant', 'R', 'Engine Starting Systems', 'risk_management', 'All starting system risk elements (hot starts, hung starts, starter duty cycle).', ARRAY[45,51]::integer[]),
  ('AM.III.R.S1-S9', 'powerplant', 'R', 'Engine Starting Systems', 'skill', 'All starting system skills (inspect, troubleshoot, starter-generator, igniter tests).', ARRAY[45,51]::integer[]),
  ('AM.III.S.K1-K10', 'powerplant', 'S', 'Engine Fuel Systems (Turbine)', 'knowledge', 'All turbine fuel system knowledge (fuel controls, governors, pumps, filters, manifolds).', ARRAY[44]::integer[]),
  ('AM.III.S.R1-R3', 'powerplant', 'S', 'Engine Fuel Systems (Turbine)', 'risk_management', 'All turbine fuel system risk elements (fuel contamination, leaks, hot starts).', ARRAY[44]::integer[]),
  ('AM.III.S.S1-S8', 'powerplant', 'S', 'Engine Fuel Systems (Turbine)', 'skill', 'All turbine fuel system skills (inspect, troubleshoot, filters, pumps, controls).', ARRAY[44]::integer[]),
  ('AM.III.T.K1-K11', 'powerplant', 'T', 'Engine Induction and Airflow (Turbine)', 'knowledge', 'All turbine induction knowledge (inlet, anti-ice, bleed air, variable geometry).', ARRAY[42,46]::integer[]),
  ('AM.III.T.R1-R3', 'powerplant', 'T', 'Engine Induction and Airflow (Turbine)', 'risk_management', 'All turbine induction risk elements (icing, FOD, bleed leaks).', ARRAY[42,46]::integer[]),
  ('AM.III.T.S1-S9', 'powerplant', 'T', 'Engine Induction and Airflow (Turbine)', 'skill', 'All turbine induction skills (inspect, troubleshoot, anti-ice, bleed air).', ARRAY[42,46]::integer[]),
  ('AM.III.U.K1-K13', 'powerplant', 'U', 'Engine Exhaust and Thrust Reverser Systems (Turbine)', 'knowledge', 'All turbine exhaust knowledge (nozzles, thrust reversers, EPR, temperature limits).', ARRAY[49]::integer[]),
  ('AM.III.U.R1-R3', 'powerplant', 'U', 'Engine Exhaust and Thrust Reverser Systems (Turbine)', 'risk_management', 'All turbine exhaust risk elements (reverser deployment, CO hazards, cracks).', ARRAY[49]::integer[]),
  ('AM.III.U.S1-S8', 'powerplant', 'U', 'Engine Exhaust and Thrust Reverser Systems (Turbine)', 'skill', 'All turbine exhaust skills (inspect, troubleshoot, reverser operation).', ARRAY[49]::integer[]),
  ('AM.III.V.K1-K12', 'powerplant', 'V', 'Auxiliary Power Units (APUs)', 'knowledge', 'All APU knowledge (operation, components, controls, electrical, bleed air).', ARRAY[28]::integer[]),
  ('AM.III.V.R1-R3', 'powerplant', 'V', 'Auxiliary Power Units (APUs)', 'risk_management', 'All APU risk elements (hot section, bleed leaks, exhaust hazards).', ARRAY[28]::integer[]),
  ('AM.III.V.S1-S8', 'powerplant', 'V', 'Auxiliary Power Units (APUs)', 'skill', 'All APU skills (inspect, troubleshoot, start, shutdown, bleed air checks).', ARRAY[28]::integer[]);


-- 3. Training plan and weeks (excludes apprentice UPDATE - no apprentices yet)
-- Seed default training plan with first 10 weeks
-- Insert the default training plan
INSERT INTO public.training_plans (id, name, description, total_weeks, is_active)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'Aviation Maintenance Technician - Standard Program',
    'Standard 130-week training program for Aviation Maintenance Technicians covering safety, ground operations, systems, and advanced maintenance procedures.',
    130,
    TRUE
)
ON CONFLICT DO NOTHING;

-- Week 1: Safety, Ground Operations & Servicing
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 1,
    'Safety, Ground Operations & Servicing', '12',
    ARRAY[
        'Understand the fundamental safety protocols in aviation maintenance',
        'Identify personal protective equipment (PPE) requirements',
        'Learn proper ground handling procedures for aircraft',
        'Understand fuel servicing safety requirements'
    ],
    'Chapter 1 of the Aviation Maintenance Technician Handbook covers essential safety practices. Focus on hazard identification, emergency procedures, and the importance of maintaining a safe work environment. Review FAA AC 43.13-1B for standard practices.',
    'Shadow your mentor during ground operations. Focus on observing how they prepare the work area, use PPE, and follow lockout/tagout procedures.',
    ARRAY[
        'What are the most common safety hazards you''ve observed in our hangar?',
        'How do you ensure proper grounding when servicing aircraft?',
        'What''s the procedure if you discover a fuel leak during servicing?'
    ],
    'Document at least 3 safety protocols you observed or practiced this week. Include photos if possible.'
);

-- Week 2: Aircraft Documentation and Record Keeping
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 2,
    'Aircraft Documentation and Record Keeping', '00',
    ARRAY[
        'Understand the importance of accurate aircraft documentation',
        'Learn to read and interpret maintenance logs and records',
        'Identify required entries in maintenance documentation',
        'Understand regulatory requirements for record keeping'
    ],
    'Review FAA regulations on aircraft maintenance records (14 CFR Part 91, 135, 121). Study examples of properly completed logbook entries and understand the difference between routine maintenance, inspections, and repairs.',
    'Practice reviewing actual aircraft logbooks under mentor supervision. Learn to identify required entries and spot incomplete or incorrect documentation.',
    ARRAY[
        'What information must be included in every maintenance log entry?',
        'How do you determine when an inspection is due?',
        'What happens if you find incomplete documentation in an aircraft log?'
    ],
    'Complete a practice logbook entry for a maintenance task you observed. Have your mentor review it for accuracy and completeness.'
);

-- Week 3: Tool Management and Calibration
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 3,
    'Tool Management and Calibration', '20',
    ARRAY[
        'Identify standard aviation maintenance tools',
        'Understand tool calibration requirements and schedules',
        'Learn proper tool storage and organization',
        'Recognize when tools require calibration or replacement'
    ],
    'Study the tool calibration requirements outlined in AC 43.13-1B. Review tool control procedures and learn about calibrated vs. uncalibrated tool usage. Understand torque wrench calibration requirements.',
    'Participate in tool inventory and calibration checks. Learn to use calibration tracking systems and identify tools that need service.',
    ARRAY[
        'How often should torque wrenches be calibrated?',
        'What are the consequences of using uncalibrated tools?',
        'How do you track tool calibration in our facility?'
    ],
    'Create a checklist for tool inspection and identify any tools in your assigned area that need calibration. Document the process.'
);

-- Week 4: Aircraft Hardware and Fasteners
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 4,
    'Aircraft Hardware and Fasteners', '20',
    ARRAY[
        'Identify common aircraft fasteners and their applications',
        'Understand thread standards (AN, MS, NAS)',
        'Learn proper torque application and installation procedures',
        'Recognize when fasteners need replacement'
    ],
    'Study AN960 washers, AN bolts, MS fasteners, and self-locking nuts. Review torque tables and installation procedures. Learn about cotter pins and safety wire applications.',
    'Practice installing and removing various fasteners under supervision. Learn to read fastener part numbers and determine proper torque values.',
    ARRAY[
        'How do you determine the correct fastener for a specific application?',
        'What is the difference between AN and MS hardware?',
        'When must fasteners be replaced rather than reused?'
    ],
    'Complete a fastener identification exercise: identify 10 different fasteners and explain their proper applications. Include photos with labels.'
);

-- Week 5: Aircraft Weight and Balance
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 5,
    'Aircraft Weight and Balance', '08',
    ARRAY[
        'Understand the importance of weight and balance calculations',
        'Learn to read weight and balance data plates',
        'Calculate center of gravity (CG) for simple configurations',
        'Recognize weight and balance limitations'
    ],
    'Study aircraft weight and balance manuals. Learn to interpret loading graphs and understand how modifications affect weight and balance. Review CG calculations and envelope limits.',
    'Observe or participate in aircraft weighing procedures. Practice calculating CG for different loading scenarios using actual aircraft data.',
    ARRAY[
        'How does fuel burn affect an aircraft''s center of gravity?',
        'What information is required to calculate weight and balance?',
        'What are the consequences of operating outside the CG envelope?'
    ],
    'Calculate the weight and balance for a hypothetical loading scenario using data from an actual aircraft in our facility. Show all calculations.'
);

-- Week 6: Fluid Systems - Hydraulics
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 6,
    'Fluid Systems - Hydraulics', '29',
    ARRAY[
        'Understand basic hydraulic system principles',
        'Identify hydraulic system components (pumps, actuators, valves)',
        'Learn proper hydraulic fluid handling and contamination control',
        'Recognize common hydraulic system failures'
    ],
    'Study hydraulic system schematics and component function. Review hydraulic fluid specifications and contamination control procedures. Learn about pressure testing and leak detection.',
    'Inspect hydraulic system components during routine maintenance. Practice fluid sampling and contamination checks. Observe hydraulic system operation and troubleshooting.',
    ARRAY[
        'What are the most common causes of hydraulic system contamination?',
        'How do you determine if hydraulic fluid needs replacement?',
        'What safety precautions are required when working with pressurized hydraulic systems?'
    ],
    'Document the hydraulic system inspection procedure. Identify any discrepancies found and explain the corrective action required.'
);

-- Week 7: Fuel Systems
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 7,
    'Fuel Systems', '28',
    ARRAY[
        'Identify fuel system components and their functions',
        'Understand fuel quality requirements and testing procedures',
        'Learn proper fuel handling and storage practices',
        'Recognize fuel system leak detection and repair procedures'
    ],
    'Study fuel system diagrams and component locations. Review fuel quality standards (ASTM D1655) and contamination detection. Learn about fuel system inspections and leak testing.',
    'Participate in fuel system inspections and fuel sampling procedures. Observe fuel handling operations and learn contamination prevention techniques.',
    ARRAY[
        'What are the requirements for fuel quality testing?',
        'How do you detect water contamination in fuel?',
        'What is the procedure for dealing with a fuel leak?'
    ],
    'Document a fuel system inspection process. Include photos of key components and explain what you''re checking for during inspection.'
);

-- Week 8: Electrical Systems Fundamentals
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 8,
    'Electrical Systems Fundamentals', '24',
    ARRAY[
        'Understand basic electrical principles (voltage, current, resistance)',
        'Read electrical wiring diagrams and schematics',
        'Identify common aircraft electrical components',
        'Learn proper wire installation and termination procedures'
    ],
    'Study electrical system theory and Ohm''s law. Review wiring diagram symbols and circuit interpretation. Learn about wire sizing, circuit protection, and electrical safety.',
    'Practice reading aircraft electrical diagrams. Observe wire routing and installation procedures. Learn to use multimeters and continuity testers safely.',
    ARRAY[
        'How do you determine the correct wire size for a given application?',
        'What are the requirements for wire installation and routing?',
        'How do you troubleshoot an electrical circuit that''s not working?'
    ],
    'Identify and trace a complete electrical circuit from the diagram. Document the circuit path and explain the function of each component.'
);

-- Week 9: Landing Gear Systems
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 9,
    'Landing Gear Systems', '32',
    ARRAY[
        'Identify landing gear system components',
        'Understand landing gear retraction and extension systems',
        'Learn proper tire and brake inspection procedures',
        'Recognize common landing gear maintenance tasks'
    ],
    'Study landing gear system operation and components. Review tire maintenance, pressure requirements, and wear limits. Learn about brake inspection and overhaul procedures.',
    'Participate in landing gear inspections and tire changes. Observe landing gear operation tests and learn proper jacking procedures for gear maintenance.',
    ARRAY[
        'What are the requirements for tire inspection and replacement?',
        'How do you properly jack an aircraft for landing gear work?',
        'What checks must be performed after landing gear maintenance?'
    ],
    'Document a landing gear inspection procedure. Include tire pressure checks, wear measurements, and any discrepancies found.'
);

-- Week 10: Engine Fundamentals
INSERT INTO public.training_plan_weeks (
    training_plan_id, week_number, title, ata_chapter,
    learning_objectives, study_materials, practical_application,
    mentor_discussion_questions, weekly_deliverable
) VALUES (
    '00000000-0000-0000-0000-000000000001', 10,
    'Engine Fundamentals', '72-80',
    ARRAY[
        'Understand basic engine operating principles',
        'Identify major engine components and their functions',
        'Learn proper engine inspection procedures',
        'Recognize common engine maintenance tasks and requirements'
    ],
    'Study engine theory and operation (reciprocating and/or turbine, depending on facility). Review engine inspection requirements and maintenance intervals. Learn about engine oil analysis and condition monitoring.',
    'Participate in engine inspections under mentor supervision. Observe oil changes, filter replacements, and other routine engine maintenance tasks.',
    ARRAY[
        'What are the key items to check during an engine inspection?',
        'How do you interpret engine oil analysis results?',
        'What maintenance tasks are required at specific engine hour intervals?'
    ],
    'Document an engine inspection process. Include inspection points, acceptable limits, and explain any discrepancies or findings.'
);
