-- Seed ATA 100 chapter list into ata_chapter table
INSERT INTO public.ata_chapter (chapter_number, title, description) VALUES
('00', 'General', NULL),
('05', 'Time Limits / Maintenance Checks', NULL),
('06', 'Dimensions & Areas', NULL),
('07', 'Lifting & Shoring', NULL),
('08', 'Leveling & Weighing', NULL),
('09', 'Towing & Taxiing', NULL),
('10', 'Parking, Mooring, Storage', NULL),
('12', 'Servicing', NULL),
('20', 'Standard Practices – Airframe', NULL),
('21', 'Air Conditioning', NULL),
('22', 'Auto Flight', NULL),
('23', 'Communications', NULL),
('24', 'Electrical Power', NULL),
('25', 'Equipment & Furnishings', NULL),
('26', 'Fire Protection', NULL),
('27', 'Flight Controls', NULL),
('28', 'Fuel', NULL),
('29', 'Hydraulic Power', NULL),
('30', 'Ice & Rain Protection', NULL),
('31', 'Indicating / Recording Systems', NULL),
('32', 'Landing Gear', NULL),
('33', 'Lights', NULL),
('34', 'Navigation', NULL),
('35', 'Oxygen', NULL),
('36', 'Pneumatic', NULL),
('38', 'Water / Waste', NULL),
('49', 'APU', NULL),
('52', 'Doors', NULL),
('53', 'Fuselage', NULL),
('54', 'Nacelles / Pylons', NULL),
('55', 'Stabilizers', NULL),
('56', 'Windows', NULL),
('57', 'Wings', NULL),
('71', 'Powerplant', NULL),
('72', 'Engine', NULL),
('73', 'Engine Fuel & Control', NULL),
('74', 'Ignition', NULL),
('75', 'Air', NULL),
('76', 'Engine Controls', NULL),
('77', 'Engine Indicating', NULL),
('78', 'Exhaust', NULL),
('79', 'Oil', NULL),
('80', 'Starting', NULL),
('81', 'Turbines', NULL),
('82', 'Water Injection', NULL),
('83', 'Accessory Gearboxes', NULL),
('84', 'Propeller', NULL),
('85', 'Propeller Control', NULL),
('91', 'Charts & Publications', NULL);
